USE [sgze]
GO

/****** Object:  Table [dbo].[ZE_EMPRESA]    Script Date: 06/05/2021 09:34:10 p. m. ******/
DROP TABLE [dbo].[ZE_EMPRESA]
GO

/****** Object:  Table [dbo].[ZE_EMPRESA]    Script Date: 06/05/2021 09:34:10 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZE_EMPRESA](
	[USUARIO] [varchar](50) NULL,
	[F_ACTUAL] [date] NULL,
	[PROGRAMA] [varchar](50) NULL,
	[ID_EMP] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[NIT] [varchar](30) NULL,
	[F_VALIDEZ] [date] NULL,
	[COD_EMP_REL] [varchar](10) NULL,
 CONSTRAINT [PK_ZE_EMPRESA] PRIMARY KEY CLUSTERED 
(
	[ID_EMP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GO

/****** Object:  Table [dbo].[ZE_TRAFOS]    Script Date: 06/05/2021 09:34:42 p. m. ******/
DROP TABLE [dbo].[ZE_TRAFOS]
GO

/****** Object:  Table [dbo].[ZE_TRAFOS]    Script Date: 06/05/2021 09:34:42 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZE_TRAFOS](
	[USUARIO] [varchar](50) NULL,
	[F_ACTUAL] [date] NULL,
	[PROGRAMA] [varchar](50) NULL,
	[ID_TRAFO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_TRAFO] [varchar](100) NULL,
	[ID_ZE] [int] NULL,
 CONSTRAINT [PK_ZE_TRAFOS] PRIMARY KEY CLUSTERED 
(
	[ID_TRAFO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
GO

/****** Object:  Table [dbo].[ZE_ZONAS_ESPECIALES]    Script Date: 06/05/2021 09:34:58 p. m. ******/
DROP TABLE [dbo].[ZE_ZONAS_ESPECIALES]
GO

/****** Object:  Table [dbo].[ZE_ZONAS_ESPECIALES]    Script Date: 06/05/2021 09:34:58 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZE_ZONAS_ESPECIALES](
	[USUARIO] [varchar](50) NULL,
	[F_ACTUAL] [date] NULL,
	[PROGRAMA] [varchar](50) NULL,
	[ID_ZE] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ZE] [nchar](10) NULL,
	[ID_EMP] [int] NULL,
	[IND_VALIDEZ_UNIV] [int] NULL,
	[IND_VALIDEZ_LIQ] [int] NULL,
	[IND_VALIDA_DBDO] [int] NULL,
	[TIP_ZE] [varchar](20) NULL,
	[F_VALID] [date] NULL,
 CONSTRAINT [PK_ZE_ZONAS_ESPECIALES] PRIMARY KEY CLUSTERED 
(
	[ID_ZE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
